HOME = /Users/macbookpro/Documents
vgerbas : vgerbas.c
	gcc vgerbas.c -I$(HOME)/prj/src/include $(HOME)/prj/src/obj/libprj.a -o vgerbas
	cp vgerbas.ori $(HOME)/prj/bin/vgerbas

new :
	rm -f vgerbas
	make vgerbas