HOME = /Users/macbookpro/Documents
vastbas : vastbas.c
	gcc vastbas.c -I$(HOME)/prj/src/include $(HOME)/prj/src/obj/libprj.a -o vastbas
	cp vastbas $(HOME)/prj/bin/vastbas
	chmod u+x $(HOME)/prj/bin/vastbas
clean :
	rm -f *~