HOME = /Users/macbookpro/Documents
vequiclass : vequiclass.c
	gcc vequiclass.c $(HOME)/prj/src/lib/equiv_class.c -I$(HOME)/prj/src/include $(HOME)/prj/src/obj/libprj.a  -o vequiclass

new :
	rm -f vequiclass
	make vequiclass
